# -*- coding: utf-8 -*-
"""Entornos Virtuales Taller - Angel

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NTfymNADNUXCmqDxiyNnAuTQxbk-ezwV

#**Introduccion a la Configuracion de Entornos Virtuales para Ciencia de Datos**

*Angel Enrique Salgado Martinez*

*Elias Buitrago Bolivar*

*S4E*

*ETITC*
"""

# Instalar el paquete python3-venv
!apt-get update -y
!apt-get install -y python 3.10 -venv

# Crear el ambiente virtual
!python3 -m venv data_sciencie_env

!pip install virtualenv

# Activar el entorno virtual
!source data_sciencie_env/bin/activate

# Instalar bibliotecas en el entorno virtual
!data_sciencie_env/bin/pip install numpy pandas matplotlib seaborn scikit-learn seaborn plotly bokeh dash

# Desactivar el entorno virtual
!deactivate

# Eliminar el entorno virtual
!rm -rf data_sciencie_env

# Archivo requirements.txt
dependencies = """
pandas==2.2.2
numpy==1.26.0
scikit-learn==1.5.2
matplotlib==3.9.2
seaborn==0.13.2
plotly==5.3.1
bokeh==3.4.0
dash==2.18.2
"""

# Crear el archivo requirements.txt
with open('requirements.txt', 'w') as f:
    f.write(dependencies)

print("El archivo 'requirements.txt' ha sido creado correctamente.")

!pip install -r requirements.txt

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

# Cargar el conjunto de datos
url  = "/content/drive/MyDrive/dataset.csv"
data = pd.read_csv(url, encoding='latin1')

# Mostrar las primeras cinco filas
data.head()

# Verificar valores faltantes
print(data.isnull().sum())

# Obtener estadisticas resumidas
print(data.describe())

# Filtrar datos para mostrar solo ventas exitosas (sin valores negativos en la cantidad)
data = data[data['Quantity'] > 0]

# Crear un grafico para visualizar las ventas por pais
import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10, 6))
sns.countplot(y='Country', data=data, order=data['Country'].value_counts().index)
plt.title('Ventas por País')
plt.xlabel('Cantidad de Ventas')
plt.ylabel('País')
plt.show()

"""**Explicacion de Grafica:**

La gráfica es una gráfica de barras horizontal que muestra la cantidad de ventas por país:

1. Eje horizontal (Cantidad de Ventas): Representa la cantidad de ventas realizadas. Los valores a la derecha indican más ventas.
   
2. Eje vertical (Países): Enumera los diferentes países desde donde se realizaron las compras.

3. Patrón observado:
   - Reino Unido (United Kingdom) domina claramente en ventas, con un número mucho mayor que el de cualquier otro país. Esto se puede observar porque la barra del Reino Unido es significativamente más larga que las de los demás países.
   - Otros países como Alemania, Francia, Irlanda (EIRE) y España tienen ventas, pero en una cantidad mucho menor.
   - La mayoría de los países tienen barras pequeñas o casi imperceptibles, indicando una baja participación en las ventas.

4. Esta distribución sugiere que el mercado principal de la empresa está en el Reino Unido, ya que casi todas las ventas provienen de allí, mientras que los demás países tienen una contribución mucho menor en términos de ventas.


"""

import matplotlib.pyplot as plt

# Histograma para la cantidad de ventas
data['Quantity'].hist()
plt.xlabel('Cantidad de Ventas')
plt.ylabel('Frecuencia')
plt.title('Distribución de la Cantidad de Ventas')
plt.show()

"""**Explicacion de Grafica:**

La gráfica es un histograma que muestra la distribución de la cantidad de ventas.

- En el eje X (Cantidad de Ventas), se representan los diferentes valores de cantidad de ventas.
- En el eje Y (Frecuencia), se muestra cuántas veces aparece cada rango de cantidad de ventas en los datos.

Interpretación:

La mayoría de las ventas están concentradas en el rango más bajo de la cantidad de ventas, cerca de 0. Esto indica que la mayoría de las transacciones implican pocas unidades vendidas por transacción. Las cantidades de ventas mayores son poco frecuentes o no existen en este conjunto de datos.

"""

import plotly.express as px

fig = px.scatter(data, x='Quantity', y='UnitPrice', color='Country', title='Ventas por Precio Unitario')
fig.show()

"""**Explicacion de Grafica:**

Esta gráfica muestra la relación entre la cantidad vendida (eje X) y el precio unitario (eje Y) para diferentes países.

1. Distribución de precios:
- La mayoría de las ventas se concentran en precios unitarios entre 0 y 5,000
- Hay algunos valores atípicos con precios muy altos (cerca de 15,000) y algunos negativos (cerca de -10,000)

2. Cantidad:
- Las cantidades vendidas van desde 0 hasta aproximadamente 80,000 unidades
- La mayoría de las transacciones se concentran en cantidades menores a 10,000 unidades

3. Países:
- La gráfica incluye datos de varios países europeos y otros como Australia y Japón
- Entre los países representados están:
  * Reino Unido
  * Francia
  * Australia
  * Países Bajos
  * Alemania
  * Noruega
  * Suiza
  * España
  * Polonia
  * Portugal
  * Italia
  * Bélgica
  * Lituania
  * Japón
  * Islandia
  * Islas del Canal

4. Patrones:
- Se observa una gran concentración de puntos cerca del origen (bajas cantidades y precios bajos)
- Los precios más altos tienden a corresponder a pedidos de menor cantidad
- Hay relativamente pocas transacciones de gran volumen (más de 40,000 unidades)

Se puede concluir que el negocio maneja principalmente transacciones de volumen moderado a bajo precio, con algunas ventas excepcionales de alto valor unitario pero menor cantidad.

"""

from bokeh.plotting import figure, show
from bokeh.io import output_notebook

output_notebook()

p = figure(title='Cantidad de Productos Vendidos por Fecha', x_axis_label='Fecha', y_axis_label='Cantidad de Ventas')
data['InvoiceDate'] = pd.to_datetime(data['InvoiceDate'])
sales_per_date = data.groupby(data['InvoiceDate'].dt.date)['Quantity'].sum()

p.line(x=sales_per_date.index, y=sales_per_date.values, legend_label='Ventas Diarias', line_width=2)
show(p)

"""**Explicacion de Grafica:**

Esta gráfica muestra la Cantidad de Productos Vendidos por Fecha con una línea de Ventas Diarias. Elementos clave:

1. Tendencia General:
- Se observa una tendencia ligeramente ascendente a lo largo del tiempo
- La volatilidad (variabilidad) de las ventas parece aumentar en períodos más recientes

2. Picos Notables:
- Hay dos picos muy pronunciados en la serie:
  * Uno aproximadamente en el primer tercio del período
  * Otro hacia el final del período
  * Ambos picos alcanzan aproximadamente 80,000 unidades vendidas

3. Patrón de Ventas:
- El volumen base de ventas parece oscilar entre 5,000 y 40,000 unidades
- Hay una notable variabilidad diaria en las ventas
- Se pueden observar múltiples picos menores que alcanzan alrededor de 40,000 unidades

4. Escala:
- El eje Y muestra la cantidad de ventas, que va desde 0 hasta aproximadamente 90,000 unidades
- El eje X muestra fechas, aunque el formato parece estar en notación científica

5. Observaciones:
- La frecuencia de picos de venta parece aumentar hacia el final del período
- Hay períodos de relativa estabilidad intercalados con períodos de alta volatilidad
- El nivel mínimo de ventas tiende a mantenerse por encima de las 5,000 unidades en la mayoría de los casos

"""